### PR TITLE
Install web targets directly from VS

### PR DESCRIPTION
**Pull request by shirhatti**

### CODE REVIEW

**Comment by shirhatti** [comment]
Don't know how I totally missed this🤦‍♂️

**Comment by christianacca** [comment]
Why closed and not merged?

**Comment by shirhatti** [comment]
@christianacca The WebBuildTools feature add a lot more than just the Web Targets so we're exploring other to get the web targets without bringing in all that excess cruft.

**Comment by ccrowhurstram** [comment]
Thanks @shirhatti for the info

**Pull request closed without merging**
