### PR TITLE
Fix indentation of WCF docker files.

### LINKED ISSUE #331: Apply standard formatting convention to WCF dockerfiles.
For docker files merged via #318

The standard formatting convention used within Dockerfiles is the left align the Dockerfile instructions and indent multi-line content. This helps with readability.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* Fixes #331

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
Looks like the ASP net docker files were fine.

**Comment by StephenBonikowsky** [comment]
Thanks for clarifying the process, I'll make sure to do that with all future changes.

**Comment by MichaelSimons** [comment]
Merging since wcf is green.

**Comment by StephenBonikowsky** [comment]
Thanks

**Pull request merged**
