### PR TITLE
Add environment controller

### PR DESCRIPTION
**Pull request by richlander**
This change enables getting the same info as the website, but via an API call. Seems like a good idea!

### CODE REVIEW

**Review by mthalman — COMMENTED** [review]
Add the same info to samples\aspnetapp as well?

**Comment by mthalman** [comment]
@richlander - Reminder on this one. Can you apply the changes to the aspnetapp sample as well?

**Comment by MichaelSimons** [comment]
@richlander - gentle ping.  This is should be updated or closed.

**Comment by MichaelSimons** [comment]
Closing as stale.  @richlander - feel free to update and re-open.

**Pull request closed without merging**
