### PR TITLE
Fix MAR search links with trailing slash

### PR DESCRIPTION
**Pull request by lbussell**
The MAR link https://mcr.microsoft.com/catalog?search=dotnet/framework/ results in a page that says "Sorry, we encountered an error. Please try again later". Removing the trailing slash fixes it, so I've adjusted the templates accordingly.

image

### CODE REVIEW

**Review by mthalman — APPROVED** [review]
This is fine as a temporary measure.

I've filed an issue for MAR because this should get fixed: https://github.com/microsoft/containerregistry/issues/171. We really do want the `dotnet/` query to work properly to avoid getting hits on other teams' .NET-related repos but not within the scope of the `dotnet/` repo.

**Comment by lbussell** [comment]
> I've filed an issue for MAR...

Thanks, I threw that issue in the tracking column of the .NET Docker board.

**Comment by lbussell** [comment]
I fixed other broken links that were upsetting the link checker - the same as https://github.com/dotnet/dotnet-docker/pull/5923/commits/3562f21dc388f9dc07e4e2aab5351a1d24b813a5

**Comment by lbussell** [comment]
Build failure is https://github.com/microsoft/dotnet-framework-docker/issues/1117, merging around that since it's unrelated to changes.

**Pull request merged**
