### PR TITLE
[WIP] Dummy PR to test CI

### PR DESCRIPTION
**Pull request by ravimeda**

### CODE REVIEW

**Comment by ravimeda** [comment]
@dotnet-bot test "WindowsServerCore-ltsc2016 - 4. Dockerfiles" please
@dotnet-bot test "WindowsServerCore-ltsc2016 - 3.5 Dockerfiles" please

**Comment by MichaelSimons** [comment]
@dotnet-bot test ci please

**Comment by MichaelSimons** [comment]
@dotnet-bot test "WindowsServerCore-ltsc2016 - 4. Dockerfiles" please
@dotnet-bot test "WindowsServerCore-ltsc2016 - 3.5 Dockerfiles" please
@dotnet-bot test "WindowsServerCore-1709 - 4. Dockerfiles" please
@dotnet-bot test "WindowsServerCore-1709 - 3.5 Dockerfiles" please

**Comment by ravimeda** [comment]
@dotnet-bot test "WindowsServerCore-ltsc2016 - 4. Dockerfiles" please
@dotnet-bot test "WindowsServerCore-ltsc2016 - 3.5 Dockerfiles" please
@dotnet-bot test "WindowsServerCore-1709 - 4. Dockerfiles" please
@dotnet-bot test "WindowsServerCore-1709 - 3.5 Dockerfiles" please

**Comment by ravimeda** [comment]
CI is working correctly now.

**Pull request closed without merging**
